# -*- coding: utf-8 -*-
"""Despliegue_NN_Redneuronal .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kP6cWgxkT27ksjB32j9tfhv0WySxrHnj
"""

import pandas as pd # manipulacion dataframes
import numpy as np # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo_rn1.pkl'
modelo, labelencoder,variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("datos_a_predecir.csv")
#data.head()

#Aquí va la interfaz gráfica
import streamlit as st

st.title('Predicción del cluster sobre el tipo de emprendimiento')
P3050 = st.selectbox('P3050', ['1.0', '2.0', '3.0', '4.0', '5.0'])
P3051 = st.selectbox('P3051', ['1.0', '2.0', '3.0', '4.0', '5.0','6.0'])
P639  = st.selectbox('P639',  ['1.0', '2.0', '3.0', '4.0', '5.0'])
P3052 = st.selectbox('P3052', ['1.0', '2.0', '3.0', '4.0', '5.0','6.0'])
Ubic_geografica = st.selectbox('Ubicación geográfica', ['Norte', 'Sur', 'Oriente', 'Occidente'])
Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])
Edad = st.selectbox('Edad', ['Adulto Joven', 'Adulto', 'Adulto Mayor'])
Nom_comercial = st.selectbox('Nom_comercial', ['Si', 'No'])
Act_economica = st.selectbox('Actividad económica', ['sector_primario', 'industria_manufacturera', 'comercio', 'servicios'])

datos = [[P3050, P3051, P639, P3052, Ubic_geografica, Sexo, Edad, Nom_comercial, Act_economica]]
data = pd.DataFrame(datos, columns=['P3050','P3051','P639','P3052','Ubic_geografica','Sexo','Edad','Nom_comercial','Act_economica'])

data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['P3050','P3051','P639','P3052','Ubic_geografica','Sexo','Nom_comercial','Act_economica'], drop_first=False, dtype=int) #Despliegue siempre drop_first en false
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Hacemos la predicción con el modelo

Y_fut = modelo.predict(data_preparada)
print(Y_fut)

data['Predicción']=labelencoder.inverse_transform(Y_fut)
data.head()

data